POST http://localhost:3000/api/create-coa
Content-Type: application/json

{
  "comic_title": "Stan Lee Unscripted",
  "issue_number": "1",
  "signed_by": "Clayton Crain, Roy Thomas, Jonathan Bolerjack",
  "signed_date": "2025-10-09",
  "signed_location": "New York Comic Con",
  "witnessed_by": "Metaverse Comics"
}
